### ISSUE TITLE
Remove Flask-API extension usage

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/alerting#33]
Currently tendrl-alerting module is using flask api extension to get a server error code.
The package not available in epel or any other repo and the source of this extension also
not available in github or anywhere to build. So its better we can remove this extension usage
in our tendrl-alerting.

**Comment by mbukatov** [comment]
Could we close this issue?

**Comment by anmolbabu** [comment]
@mbukatov I'll close it

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat Please close this as its PR is already merged
