### ISSUE TITLE
yaml content should not be inlined in python source files

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/alerting#42]
Original issue: Tendrl/commons#201

**Comment by anmolbabu** [comment]
Fix is posted in https://github.com/Tendrl/alerting/pull/41 as in https://github.com/Tendrl/alerting/pull/41/files#diff-29272db9819e2eed1707182214645b6bL2

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat Please close this issue. The PR to fix this has been merged..
