### ISSUE TITLE
alerting package is missing

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/alerting#45]
If you look at Tendrl repo there is no package tendrl-alerting. I think it should be.
@TimothyAsir Please look at this issue.

**Comment by nthomas-redhat** [comment]
@mkudlej This is built already and available in copr. Closing this issue

**Comment by mkudlej** [comment]
@nthomas-redhat Yes, it is in copr repo, but still one important thing is missing https://github.com/Tendrl/documentation/issues/79
