### ISSUE TITLE
Re-factor alerting code to extend/use common module

### ISSUE THREAD

**Issue by shtripat** [Tendrl/alerting#9]
The common module provides all the base classes for flows, atoms, manager, job queue handler, persister and contains all the utilities which are generic in nature like exceptions, command executor, service manager and package installer. The alerting modules should extend/use these common module changes.

**Comment by r0h4n** [comment]
Any updates? Add spec issue link here

**Comment by shtripat** [comment]
Linked to spec issue https://github.com/Tendrl/specifications/issues/31

Code changes can start once initial project PR gets merged. Should be assigned to @anmolbabu

**Comment by shtripat** [comment]
@anmolbabu is it still open?

**Comment by anmolbabu** [comment]
@shtripat This can be closed. But, I have no permissions to close it... Please close it...

**Comment by shtripat** [comment]
Closing as confirmed by @anmolbabu
